WebApplication-VisualStudio/WebApplication/Controllers/ArchivosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.ViewModel;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ArchivosController : Controller
    {
        //
        // GET: /Archvios/
        public ActionResult Index(int? id)
        {
            if (Session["objUser"] != null)
            {
                BitacoraArchivosViewModel objViewModel = new BitacoraArchivosViewModel();
                if (id.HasValue) objViewModel.CargarDatos(id.Value);
                else objViewModel.CargarDatos();
                return View("BitacoraArchivos", objViewModel);
            }
            return RedirectToAction("Login", "Home");
        }


        [HttpPost]
        public ActionResult Add(BitacoraArchivosViewModel objView)
        {
            trabajo_partialEntities context = new trabajo_partialEntities();
            HttpPostedFileBase file = Request.Files[0];
            if (objView == null)
            {
                return View();
            }
            string name = file.FileName;
            string ext = System.IO.Path.GetExtension(name);
            objView.obj.Extension = ext;
            objView.obj.IdIncidencia = objView.SelectedIncidencia;
            objView.obj.Estado = "ACT";
            //TODO mettre dans l'objet
            System.IO.MemoryStream target = new System.IO.MemoryStream();
            file.InputStream.CopyTo(target);
            objView.obj.Archivo1 = target.ToArray();
            context.Archivo.Add(objView.obj);
            context.SaveChanges();

            return Json("ok");
        }

        [HttpPost]
        public ActionResult Edit(BitacoraArchivosViewModel objView)
        {
            trabajo_partialEntities context = new trabajo_partialEntities();
            Archivo original = context.Archivo.FirstOrDefault(x => x.IdArchivo == objView.obj.IdArchivo);
            if (objView == null)
            {
                return Json("error : not found objView");
            }
            if (original == null)
            {
                return Json("error : not found original in database");
            }
            if (original.Nombre == objView.obj.Nombre && original.IdIncidencia == objView.SelectedIncidencia)
            {
                return Json("notmodified");
            }
            original.Nombre = objView.obj.Nombre;
            original.IdIncidencia = objView.SelectedIncidencia;
            context.SaveChanges();
            return Json("ok");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            trabajo_partialEntities context = new trabajo_partialEntities();
            Archivo original = context.Archivo.FirstOrDefault(x => x.IdArchivo == id);
            if (original == null)
            {
                return Json("not deleted : cannot find into DB", JsonRequestBehavior.AllowGet);
            }
            original.Estado = "INA";
            context.SaveChanges();

            return Json("ok", JsonRequestBehavior.AllowGet);
        }
	}
}

WebApplication-VisualStudio/WebApplication/Views/Shared/_Layout.cshtml
@{
    WebApplication.Models.User objUser = null;
    String strUsername = String.Empty;

    if (Session["objUser"] != null)
    {
        objUser = ((WebApplication.Models.User)Session["objUser"]);
        strUsername = objUser.Username;
    }
}

<!DOCTYPE html>
<html>
<head>
    <title>UPC</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css-->
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/datepicker3.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/styles.css")" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="@Url.Content("~/Content/favicon.ico")">
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!--[if lt IE 9]
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    [endif]-->

    <!--Icons-->
    <script src="@Url.Content("~/Content/lumino.glyphs.js")"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><span>UPC</span>Admin<img class="nav-brand" src="@Url.Content("~/Content/favicon1-32x32.png")"></a>


                <div class="user-menu">
                    @{
                        if (Session["objUser"] != null)
                        {
                             <div class="dropdown pull-right">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> @strUsername <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu"> <li><a href="@Url.Action("Perfil", "Home")"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Mi Cuenta</a></li>
                                    <li><a href="@Url.Action("CerrarSesion", "Home" )"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Salir</a></li>
                                </ul>
                            </div>
                        }
                        else{
                             <a href="@Url.Action("Login", "Home")"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Conectarse </a>
                        }
                    }

                </div>
            </div>

        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @{
            if (Session["objUser"] != null)
            {
                <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-1 main">
                    <div class="row">
                        <ol class="breadcrumb">
                            <li class="active"><a href="@Url.Action("Inicio", "Home")"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
                            <li class="active"><a href="@Url.Action("Index", "Incidencias")"><span class="glyphicon glyphicon-list-alt"></span> Incidencias</a></li>
                            @if (objUser.IsSupervisor==0)
                            {
                                <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Tablas Maestras <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="@Url.Action("Index", "TipoIncidencia")"> Tipo Incidencia</a></li>
                                    <li><a href="@Url.Action("Index", "EstadoIncidencia")"> Estado Incidencia</a></li>
                                </ul>
                                </li>
                                <li class="active"><a href="@Url.Action("Index", "Usuarios")"><span class="fa fa-users"></span> Usuarios</a></li>
                            }
                            <li class="active"><a href="@Url.Action("Index", "Archivos")"><span class="fa fa-folder-open"></span> Bitacora Archivos</a></li>
                            <li class="active"><a href="@Url.Action("Index", "Seguimientos")"><span class="fa fa-sticky-note"></span> Bitacora Seguimientos</a></li>
                        </ol>
                    </div><!--/.row-->
                </div>
            }
        }

        @RenderBody()
        <hr />
        <footer>
            <p>Aplicacióon  .NET Gestor de incidencias UPC - <a href="@Url.Action("About", "Home")">Información</a> - &copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    <script src="@Url.Content("~/Scripts/bootstrap-table.js")"></script>

    <script src="@Url.Content("~/Scripts/bootstrap-datepicker.js")"></script>
    <script src="@Url.Content("~/Scripts/libusescript.js")"></script>
    

    @RenderSection("scripts", required: false)

</body>
</html>